module.exports = {
    language: 'pt-br',
    articles: [
        'a',
        'de',
        'em',
        'por',
        'per',
        'o',
        'os',
        'ao',
        'aos',
        'do',
        'dos',
        'no',
        'nos',
        'pelo',
        'pelos',
        'as',
        'à',
        'às',
        'da',
        'das',
        'na',
        'nas',
        'pela',
        'pelas',
        'um',
        'uns',
        'dum',
        'duns',
        'num',
        'nums',
        'uma',
        'umas',
        'duma',
        'dumas',
        'numa',
        'numas',
        'é',
        'são',
        'e',
        'com'
    ],
    plural: [
        [/^([a-zA-z]*)a$/i, '$as'],
        [/^([a-zA-z]*)e$/i, '$es'],
        [/^([a-zA-z]*)i$/i, '$is'],
        [/^([a-zA-z]*)o$/i, '$os'],
        [/^([a-zA-z]*)u$/i, '$us'],
        [/^([a-zA-z]*)r$/i, '$res'],
        [/^([a-zA-z]*)z$/i, '$zes'],
        [/^([a-zA-z]*)al$/i, '$ais'],
        [/^([a-zA-z]*)el$/i, '$eis'],
        [/^([a-zA-z]*)ol$/i, '$ois'],
        [/^([a-zA-z]*)ul$/i, '$uis'],
        [/^([a-zA-z]*)il$/i, '$is'],
        [/^([a-zA-z]*)m$/i, '$ns'],
        [/^([a-zA-z]*)e$/i, '$es'],
        [/^([a-zA-z]*)x$/i, '$x'],
        [/^([a-zA-z]*)ao$/i, '$oes']
    ],
    irregulars: [
        ['cao', 'caes'],
        ['pao', 'paes'],
        ['mao', 'maos'],
        ['alemao', 'alemaes']
    ],
    uncountable: [],
    singular: [
        [/^([a-zA-z]*)aes$/i, '$ao'],
        [/^([a-zA-z]*)aos$/i, '$ao'],
        [/^([a-zA-z]*)oes$/i, '$ao'],
        [/^([a-zA-z]*)ais$/i, '$al'],
        [/^([a-zA-z]*)eis$/i, '$el'],
        [/^([a-zA-z]*)ois$/i, '$ol'],
        [/^([a-zA-z]*)uis$/i, '$ul'],
        [/^([a-zA-z]*)as$/i, '$a'],
        [/^([a-zA-z]*)es$/i, '$e'],
        [/^([a-zA-z]*)is$/i, '$i'],
        [/^([a-zA-z]*)os$/i, '$o'],
        [/^([a-zA-z]*)us$/i, '$u'],
        [/^([a-zA-z]*)res$/i, '$r'],
        [/^([a-zA-z]*)zes$/i, '$z'],
        [/^([a-zA-z]*)is$/i, '$il'],
        [/^([a-zA-z]*)ns$/i, '$m']
    ]
};
